import{TILE,ENEMIES}from'../config.js';
let nextId=1;export class Enemy{constructor(type,x,y,difficulty){this.id=nextId++;this.configure(type,x,y,difficulty)}configure(type,x,y,d){const c=ENEMIES[type];Object.assign(this,{type,x,y,active:true,state:'patrol',stateTime:0,targetX:x,targetY:y,lastSeen:null,alert:0,attackCd:Math.random(),hitFlash:0,stagger:0,coverTime:0});this.maxHp=c.hp*d.enemyHealth;this.hp=this.maxHp;this.speed=c.speed;this.damage=c.damage*d.enemyDamage;this.range=c.range;this.rate=c.rate;this.radius=c.radius;this.score=c.score;this.color=c.color;this.name=c.name;return this}update(dt,world){if(!this.active)return;this.hitFlash=Math.max(0,this.hitFlash-dt);this.stagger=Math.max(0,this.stagger-dt);this.attackCd-=dt;this.stateTime+=dt;const p=world.player,dx=p.x-this.x,dy=p.y-this.y,dist=Math.hypot(dx,dy),visible=world.lineOfSight(this.x,this.y,p.x,p.y);if(visible&&dist<700){this.lastSeen={x:p.x,y:p.y};this.alert=4;if(this.state==='patrol'||this.state==='search')this.setState('chase')}this.alert-=dt;if(this.hp<this.maxHp*.22&&this.type!=='boss'&&this.type!=='fast'&&this.state!=='retreat')this.setState('retreat');if(this.stagger>0)return;
if(this.state==='patrol'){if(this.stateTime>2+Math.random()*2){this.targetX=this.x+(Math.random()-.5)*TILE*3;this.targetY=this.y+(Math.random()-.5)*TILE*3;this.setState('investigate')}this.moveToward(this.targetX,this.targetY,dt*.45,world)}
else if(this.state==='investigate'){this.moveToward(this.targetX,this.targetY,dt*.65,world);if(this.stateTime>3)this.setState('search')}
else if(this.state==='search'){if(this.lastSeen)this.moveToward(this.lastSeen.x,this.lastSeen.y,dt*.55,world);if(this.stateTime>4)this.setState('patrol')}
else if(this.state==='retreat'){this.moveAway(p.x,p.y,dt,world);if(dist>480||this.stateTime>3)this.setState('attack')}
else if(this.state==='chase'){const desired=this.type==='fast'?38:this.range*.72;if(dist>desired)this.moveToward(p.x,p.y,dt,world);else if(dist<desired*.55&&this.type!=='fast')this.moveAway(p.x,p.y,dt*.55,world);if(visible&&dist<this.range)this.setState('attack')}
else if(this.state==='attack'){if(!visible){this.setState('search')}else{if(this.type!=='fast'&&dist<this.range*.45)this.moveAway(p.x,p.y,dt*.35,world);if(dist>this.range*1.15)this.setState('chase');else if(this.attackCd<=0){this.attackCd=1/this.rate*(.75+Math.random()*.5);const accuracy=Math.max(.18,1-dist/(this.range*1.5));if(Math.random()<accuracy)world.player.damage(this.damage);world.bus.emit('enemyShot',{enemy:this});if(this.type==='boss'&&Math.random()<.3)world.spawnReinforcement(this.x,this.y)}}}
if(this.alert<=0&&this.state!=='patrol')this.setState('search')}
setState(s){this.state=s;this.stateTime=0}moveToward(tx,ty,dt,w){this.move(tx-this.x,ty-this.y,dt,w)}moveAway(tx,ty,dt,w){this.move(this.x-tx,this.y-ty,dt,w)}move(dx,dy,dt,w){const m=Math.hypot(dx,dy)||1,v=this.speed*dt,nx=this.x+dx/m*v,ny=this.y+dy/m*v;if(w.isWalkable(nx,this.y,this.radius))this.x=nx;else this.y+=(Math.random()-.5)*v;if(w.isWalkable(this.x,ny,this.radius))this.y=ny;else this.x+=(Math.random()-.5)*v}takeDamage(n,headshot,bus){this.hp-=n;this.hitFlash=.1;this.stagger=headshot?.14:.06;this.alert=5;this.setState('chase');bus.emit('hit',{enemy:this,headshot,damage:n});if(this.hp<=0){this.active=false;bus.emit('kill',{enemy:this,headshot});return true}return false}}
