import{MAP,TILE,DIFFICULTY}from'./config.js';import{EventBus}from'./core/EventBus.js';import{SaveSystem}from'./core/SaveSystem.js';import{AudioManager}from'./core/AudioManager.js';import{InputManager}from'./core/InputManager.js';import{Player}from'./entities/Player.js';import{WeaponSystem}from'./systems/WeaponSystem.js';import{ParticlePool}from'./systems/ParticlePool.js';import{SpawnManager}from'./systems/SpawnManager.js';import{MissionManager}from'./systems/MissionManager.js';import{Renderer}from'./render/Renderer.js';import{UIManager}from'./ui/UIManager.js';
export class Game{constructor(){this.canvas=document.getElementById('game');this.bus=new EventBus;this.save=new SaveSystem;this.settings=this.save.data.settings;this.audio=new AudioManager(this.bus,this.settings);this.input=new InputManager(this.canvas,this.settings,this.bus);this.player=new Player(this.bus);this.weapons=new WeaponSystem(this.bus);this.particles=new ParticlePool;this.spawn=new SpawnManager(this);this.mission=new MissionManager(this.bus);this.renderer=new Renderer(this.canvas,document.getElementById('minimap'),this);this.ui=new UIManager(this);this.mode='campaign';this.difficulty=DIFFICULTY[this.settings.difficulty];this.running=false;this.paused=false;this.score=0;this.kills=0;this.headshots=0;this.combo=1;this.comboTimer=0;this.cameraShake=0;this.pickups=[];this.last=performance.now();this.bind();this.setupMenu();requestAnimationFrame(t=>this.loop(t))}
bind(){this.bus.on('kill',({enemy,headshot})=>{this.kills++;if(headshot)this.headshots++;this.combo=this.comboTimer>0?Math.min(10,this.combo+1):1;this.comboTimer=4;this.score+=Math.round(enemy.score*this.combo*(headshot?1.3:1));this.cameraShake=Math.max(this.cameraShake,enemy.type==='boss'?18:7);this.particles.emit(enemy.x,enemy.y,enemy.color,enemy.type==='boss'?36:14,150);if(Math.random()<.25)this.dropPickup(enemy.x,enemy.y);this.mission.onKill(this.spawn)});this.bus.on('hit',({enemy,headshot})=>this.particles.emit(enemy.x,enemy.y,headshot?'#ffcf68':'#ff6479',headshot?10:5,90));this.bus.on('shot',w=>{this.cameraShake=Math.max(this.cameraShake,w.recoil*55)});this.bus.on('playerDead',()=>this.end(false));this.bus.on('enemyShot',({enemy})=>this.particles.emit(enemy.x,enemy.y,'#ff9a6d',3,35))}
setupMenu(){document.querySelectorAll('button[data-action]').forEach(btn=>btn.addEventListener('click',()=>{this.audio.ensure();this.bus.emit('ui');const a=btn.dataset.action;if(a==='new')this.ui.show('difficulty');if(a==='continue')this.start('campaign',this.save.data.progress.checkpoint);if(a==='survival')this.start('survival',0);if(a==='practice')this.start('practice',0);if(a==='settings'){this.syncSettings();this.ui.show('settings')}if(a==='controls')this.ui.show('controls');if(a==='back')this.ui.show(this.ui.previous==='pause'?'pause':'menu');if(a==='resume')this.resume();if(a==='restart')this.start(this.mode,this.mode==='campaign'?this.save.data.progress.checkpoint:0);if(a==='quit')this.quit();if(a==='save-settings')this.applySettings()}));document.querySelectorAll('[data-difficulty]').forEach(btn=>btn.addEventListener('click',()=>{this.settings.difficulty=btn.dataset.difficulty;this.save.save();this.start('campaign',0)}));document.getElementById('continue-btn').disabled=this.save.data.progress.checkpoint===0}
syncSettings(){document.getElementById('sensitivity').value=this.settings.sensitivity;document.getElementById('volume').value=this.settings.volume;document.getElementById('quality').value=this.settings.quality;document.getElementById('shake').checked=this.settings.shake}
applySettings(){this.settings.sensitivity=+document.getElementById('sensitivity').value;this.settings.volume=+document.getElementById('volume').value;this.settings.quality=document.getElementById('quality').value;this.settings.shake=document.getElementById('shake').checked;this.audio.setVolume(this.settings.volume);this.save.save();this.renderer.resize();this.ui.show(this.ui.previous==='pause'?'pause':'menu')}
start(mode='campaign',checkpoint=0){this.mode=mode;this.difficulty=DIFFICULTY[this.settings.difficulty];this.player.reset(checkpoint);this.weapons.reset();this.spawn.reset();this.mission.reset(mode);this.pickups=[];this.particles=new ParticlePool;this.score=checkpoint*1500;this.kills=0;this.headshots=0;this.combo=1;this.comboTimer=0;this.cameraShake=0;this.running=true;this.paused=false;this.ui.show(null);document.getElementById('boss-wrap').classList.add('hidden');if(mode==='practice'){['soldier','fast','heavy','ranged'].forEach((t,i)=>{const e=this.spawn.spawn(t);e.x=(6+i*2)*TILE;e.y=7*TILE})}else this.spawn.startWave(checkpoint?checkpoint+1:1);this.canvas.requestPointerLock?.();this.last=performance.now()}
resume(){this.paused=false;this.ui.show(null);this.canvas.requestPointerLock?.();this.last=performance.now()}
pause(){if(!this.running)return;this.paused=true;document.exitPointerLock?.();this.ui.show('pause')}
quit(){this.running=false;this.paused=false;document.exitPointerLock?.();this.ui.show('menu')}
end(victory){if(!this.running)return;this.running=false;document.exitPointerLock?.();this.save.record(this.score,victory);setTimeout(()=>this.ui.result(victory),350)}victory(){this.end(true)}checkpoint(){if(this.mode==='campaign'&&this.spawn.wave<5){this.save.checkpoint(Math.min(2,Math.floor(this.spawn.wave/2)));document.getElementById('continue-btn').disabled=false}}
isWalkable(x,y,r=12){const solid=(px,py)=>MAP[Math.floor(py/TILE)]?.[Math.floor(px/TILE)]!=='0';return !solid(x-r,y-r)&&!solid(x+r,y-r)&&!solid(x-r,y+r)&&!solid(x+r,y+r)}lineOfSight(x1,y1,x2,y2){const d=Math.hypot(x2-x1,y2-y1),steps=Math.ceil(d/16);for(let i=1;i<steps;i++){const t=i/steps;if(!this.isWalkable(x1+(x2-x1)*t,y1+(y2-y1)*t,2))return false}return true}spawnReinforcement(x,y){if(this.spawn.enemies.length>18)return;const e=this.spawn.spawn(Math.random()<.5?'fast':'soldier');e.x=x+(Math.random()-.5)*100;e.y=y+(Math.random()-.5)*100}
traceShot(angle,range,w){let best=null,bestScore=Infinity;for(const e of this.spawn.enemies){if(!e.active)continue;const dx=e.x-this.player.x,dy=e.y-this.player.y,dist=Math.hypot(dx,dy);if(dist>range||!this.lineOfSight(this.player.x,this.player.y,e.x,e.y))continue;let diff=Math.atan2(dy,dx)-angle;while(diff>Math.PI)diff-=Math.PI*2;while(diff<-Math.PI)diff+=Math.PI*2;const tolerance=Math.atan2(e.radius,dist)*1.25;if(Math.abs(diff)<tolerance&&Math.abs(diff)*dist<bestScore){best=e;bestScore=Math.abs(diff)*dist}}if(best){const headshot=this.player.pitch<-.055&&w.id!=='shotgun';const dist=Math.hypot(best.x-this.player.x,best.y-this.player.y),falloff=Math.max(.45,1-dist/w.range*.55),damage=w.damage*falloff*(headshot?w.head:1);best.takeDamage(damage,headshot,this.bus);return best}const ray=this.renderer.castRay(angle,range);this.particles.emit(ray.x,ray.y,'#7ddfff',4,35);return null}
closestEnemyInCone(range,cone){let best=null,d0=range;for(const e of this.spawn.enemies){const dx=e.x-this.player.x,dy=e.y-this.player.y,d=Math.hypot(dx,dy),a=Math.abs(Math.atan2(dy,dx)-this.player.angle);if(d<d0&&a<cone&&this.lineOfSight(this.player.x,this.player.y,e.x,e.y)){best=e;d0=d}}return best}dropPickup(x,y){const low=this.player.health<55?'health':this.player.armor<40?'armor':'ammo';this.pickups.push({x,y,type:low,r:18,t:0})}updatePickups(dt){for(const p of this.pickups){p.t+=dt;if(Math.hypot(p.x-this.player.x,p.y-this.player.y)<35){if(p.type==='health')this.player.heal(30);else if(p.type==='armor')this.player.addArmor(35);else this.weapons.addAmmo(45);p.dead=true;this.bus.emit('pickup',p.type)}}this.pickups=this.pickups.filter(p=>!p.dead)}
update(dt){this.input.pollGamepad();if(this.input.tap('pause')||this.input.gamepad.pause){this.pause();return}this.player.update(dt,this.input,MAP,this.settings);this.weapons.update(dt,this.input,this);if(this.input.tap('melee')||this.input.gamepad.melee)this.weapons.melee(this);this.spawn.update(dt);this.particles.update(dt);this.updatePickups(dt);this.comboTimer-=dt;if(this.comboTimer<=0)this.combo=1;this.cameraShake*=Math.pow(.01,dt);this.ui.update(dt);this.input.consume()}
loop(t){const dt=Math.min(.033,(t-this.last)/1000||0);this.last=t;if(this.running&&!this.paused)this.update(dt);if(this.running)this.renderer.render();requestAnimationFrame(n=>this.loop(n))}}
